### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ezeakeal** [kylesayrs/ATAK_push_cots#1]
Hi there,
Can a license be given to this repo to clarify the rights (if any) that are granted?
As it stands there are no rights for re-use: https://opensource.stackexchange.com/a/1721
Thanks for the great work!

**Comment by kylesayrs** [comment]
Hi @ezeakeal, thanks for the kind words!

I've included the MIT license which gives users full autonomy over what they do with the software.

Thanks for bringing this to my attention
-Kyle
