### ISSUE TITLE
tests mock working directory 

### ISSUE THREAD

**Issue by davidcarlsonSEE** [kylesayrs/ATAK_push_cots#4]
when I run test_push_cot in the tests directory I get this path error.   I must be missing something on my pwd where I'm executing these py files?

Exception has occurred: ModuleNotFoundError
No module named 'tests'
  File "/root/source/python/pushcots/ATAK_push_cots/tests/test_push_cot.py", line 6, in <module>
    from tests.mock import MockClient
ModuleNotFoundError: No module named 'tests'

**Comment by davidcarlsonSEE** [comment]
Testing with MockClient.py

in examples/attachments/main.py change:
`with CotServer("127.0.0.1", 8000) as server:
        server.push_cot(cot_config, "127.0.0.1", 8001)`


run two terminals even a windows WSL system works.
on terminal one:
cd into tests/mock then run 'python3 MockClient.py". This will start a listener on 127.0.0.1:8001.

on terminal two from the ATAK_push_cots directory run:
root@DEVELOPER9:~/source/python/pushcots/ATAK_push_cots# python3 examples/attachments/main.py

**Comment by kylesayrs** [comment]
You'll want to run the tests from within the root directory
```
cd ATAK_push_cots
python3 -m pytest tests
```
